apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "familybot.fullname" . }}
  labels:
    {{- include "familybot.labels" . | nindent 4 }}
data:
  WEBHOOK_URL: {{ .Values.config.webhookURL | quote }}
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
  DB_PATH: {{ .Values.config.dbPath | quote }}
  TIMEZONE: {{ .Values.config.timezone | quote }}
  MORNING_TIME: {{ .Values.config.morningTime | quote }}
  EVENING_TIME: {{ .Values.config.eveningTime | quote }}
  DEBT_MANAGER_URL: {{ .Values.config.debtManagerURL | quote }}
  CALDAV_URL: {{ .Values.config.caldavURL | quote }}
  {{- if .Values.config.caldavCalendarID }}
  CALDAV_CALENDAR_ID: {{ .Values.config.caldavCalendarID | quote }}
  {{- end }}
