apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: familybot
  namespace: familybot
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - family.tazhate.com
      secretName: familybot-tls
  rules:
    - host: family.tazhate.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: familybot
                port:
                  number: 8080
